### ISSUE TITLE
Better error handling for HTTP Operations

### ISSUE THREAD

**Issue by DLMousey** [enderstudy/Youtube-Microservice#3]
Currently error handling for the HTTP Operations in [HttpRequestSender.java](https://github.com/enderstudy/Youtube-Microservice/blob/master/src/main/java/HttpRequestSender.java) rely on an exception being thrown to indicate anything went wrong.

Some testing reveals this is... not really the case, i pointed the app at the production API which i'd forgotten to deploy the new endpoints for syncing metadata to (i know, 11/10 progress tracking right there) and received 404 errors because of course, endpoints weren't there.
Despite this, "Synced ok!" messages were still appearing in the console. 

Some additional checking needs to be added to ensure the request did actually return a 200/201 and error out as appropriate.

**Comment by b0n541** [comment]
I would take it.
